<?php

/**
 * Implements hook_menu().
 */
function client_log_notify_coach_menu() {
  $items['notifications'] = array(
    'page callback' => '_notifications_populate',
    'type' => MENU_CALLBACK,
    'access arguments' => TRUE,
  );

  $items['clear-notification'] = array(
    'page callback' => '_notifications_status_response',
    'type' => MENU_CALLBACK,
    'access arguments' => TRUE,
  );

  $items['coach-dashboard'] = array(
    'page callback' => 'get_all_client_data_for_coach',
    'type' => MENU_CALLBACK,
    'access arguments' => TRUE,
  );

  return $items;
}

function _notifications_populate() {
  global $user;
  $messages = get_notifications_for_coach($user->uid);
  $messages['popup_messages'] = $messages;

  if (count($messages) == 0) {
    $messages = array(0 => array("message" => "No notification message is available", "id" => "nomsg"));
  }

  $output = theme('notification_popup', array('coach_messages' => $messages));

  return $output;

}


/**
 * Implements hook_theme().
 */
function client_log_notify_coach_theme() {
  return array(
    'notification_popup' => array(
      'template' => 'notification_popup',
      'variables' => array('coach_messages' => NULL,),
      'path' => drupal_get_path('module', 'client_log_notify_coach') . '/templates',
    ),

    'coach_dashboard' => array(
      'template' => 'coach_dashboard',
      'variables' => array('coach_dashboard' => NULL,),
      'path' => drupal_get_path('module', 'client_log_notify_coach') . '/templates',
    ),
  );
}

function client_log_notify_coach_node_presave($node) {
  global $user;

  if ($node->type == 'daily_log') {
    $plan_value = isset($node->field_was_today_on_plan['und'][0]['value'])?$node->field_was_today_on_plan['und'][0]['value']: NULL;

    // Get the coach id under which the client is trained
    $query = db_select('field_data_field_client_ref', 'at')
      -> fields('coach', array('field_coach_ref_target_id'));
    $query->join('field_data_field_coach_ref', 'coach', "coach.entity_id = at.entity_id");
    $query->condition('at.bundle', 'goals');
    $query->condition('at.field_client_ref_target_id', $user->uid);
    $coach_id = $query->execute()->fetchCol();
    $coach_id = !empty($coach_id)? $coach_id[0] : NULL;

    // Get Client Name from users table
    $client_name = db_query("Select name from users where uid =" . $user->uid . "")->fetchCol();

    $client_name = !empty($client_name)? $client_name[0]: NULL;
    $message = $client_name . " has replied " . $plan_value;

    // Insert in table to notify coach about this.
    $nid = db_insert('notify_coach')
        ->fields(array(
          'client_id' => $user->uid,
          'message' => $message,
          'status' => 0,
          'time_stamp' => REQUEST_TIME,
          'coach_id' => $coach_id,
        ))
    ->execute();
  }
}

function get_notifications_for_coach($uid) {
  $query = db_select('coach_notify', 'at')
        -> fields('at', array('message' , 'time_stamp', 'seq_id'))
        -> condition('at.user_id', $uid)
        -> condition('at.status', 0)
        -> orderBy('at.time_stamp', 'DESC');

  $messages = $query->execute()->fetchAll();

  $message = array();
  if (isset($messages)) {
    foreach($messages as $key => $value) {
      $message[$key]['message'] =  $value->message;
      $message[$key]['id']  = $value->seq_id;
      $message[$key]['time_stamp']  = $value->time_stamp;
    }
  }

  return $message;
}


function _notifications_status_response() {
  $id = $_POST['id'];
  update_msg_status_co_op($id);
}


/**
 * Update message status for co op
 */
function update_msg_status_co_op($id) {
  $num_updated = db_update('notify_coach')
  ->fields(array(
    'status' => 1,
  ))
  ->condition('seq_id', $id, '=')
  ->execute();
}



/**
 * get total no of clients under particular coach
 */
function get_total_no_of_clients_under_each_coach($uid) {
  $query = db_select('field_data_field_client_ref', 'at')
      -> fields('at', array('field_client_ref_target_id'));
  $query->join('field_data_field_coach_ref', 'coach', "coach.entity_id = at.entity_id");
  $query->condition('at.bundle', 'goals');
  $query->condition('coach.field_coach_ref_target_id', $uid);
  $client_id = $query->execute()->rowCount();

  return $client_id;
}

/**
 * get end date and find remaining days
 */
function get_remaining_days($nid) {
  $node = node_load($nid);

  if (isset($node->field_goal_date['und'][0]['value2']) && !empty($node->field_goal_date['und'][0]['value2'])) {
    $end_date = explode('-', $node->field_goal_date['und'][0]['value2']);
    if (!empty($end_date)) {
      $day = explode(' ', $end_date[2]);
    }

    $end_date = $end_date[0] . "/" . $end_date[1] . "/" . $day[0];
    $end_date_timestamp = strtotime($end_date);

    $current_date = time();

    $days = ceil(($end_date_timestamp - $current_date) / (60 * 60 * 24));

    if ($days == -0) {
      $days = 0;
    }

    return $days;
   }
}


/**
 * Implements hook_form_alter()
 */
function client_log_notify_coach_form_alter(&$form, &$form_state, $form_id) {
  $form['title']['#access'] = FALSE;
  if ($form_id == 'goals_node_form') {
    $no_value = isset($form['field_client_ref']['und']['#options']['_none'])?$form['field_client_ref']['und']['#options']['_none']: NULL;
    $eligible_clients = array(0 => $no_value) + get_eligible_clients('goals');
    $form['field_client_ref']['und']['#options'] = $eligible_clients;
  }
  elseif ($form_id == 'path_to_fitness_node_form'){
   $no_value = isset($form['field_client_ref']['und']['#options']['_none'])?$form['field_client_ref']['und']['#options']['_none']: NULL;
    $eligible_clients = array(0 => $no_value) + get_eligible_clients('path_to_fitness');
    $form['field_client_ref']['und']['#options'] = $eligible_clients;
  }
  elseif ($form_id == 'check_in_node_form') {
    $no_value = isset($form['field_client_ref']['und']['#options']['_none'])?$form['field_client_ref']['und']['#options']['_none']: NULL;
    $eligible_clients = array(0 => $no_value) + get_related_clients();
    $form['field_client_ref']['und']['#options'] = $eligible_clients;
  }
}

/**
 * Fetch eligible clients for "goal", "path to fitness" when creating a new goal or path to fitness.
 */
function get_eligible_clients($bundle) {
  $role_id = db_query("Select rid from role where name = 'client'")->fetch();
  $client_name = array();

  if (!empty($role_id)) {
    $rid = $role_id->rid;
  }

  $query = db_select('users', 'at')
    ->distinct()
    -> fields('at', array('uid','name'));
  $query-> leftjoin('field_data_field_client_ref', 'client', "client.field_client_ref_target_id = at.uid");
  $query->join('users_roles', 'role', "role.uid = at.uid");
  $query->condition('role.rid', $rid);
  $query->condition('at.status', 1);
  $query->condition('client.bundle', $bundle);
  $query->condition('client.field_client_ref_target_id', NULL);
  $client_id = $query->execute()->fetchAllKeyed(0);

  if (!empty($client_id)) {
    return $client_id;
  }
  return array();
}

/**
 *  Fetch clients for "check in" under a particular coach
 */
function get_related_clients() {
  global $user;
  $coach_id = $user->uid;
  $role_id = db_query("Select rid from role where name = 'client'")->fetch();
  $client_name = array();

  if (!empty($role_id)) {
    $rid = $role_id->rid;
  }

  $query = db_select('node', 'n')
    ->distinct();
  $query->join('field_data_field_coach_ref', 'coach', "coach.entity_id = n.nid");
  $query->join('field_data_field_client_ref', 'client', "client.entity_id = n.nid");
  $query->join('users', 'at', "client.field_client_ref_target_id = at.uid");
  $query->join('users_roles', 'role', "role.uid = at.uid");
  $query->condition('role.rid', $rid);
  $query->condition('n.type', 'goals');
  $query->condition('coach.field_coach_ref_target_id', $coach_id);
  $query->fields('at', array('uid','name'));
  $query->condition('at.status', 1);
  $client_id = $query->execute()->fetchAllKeyed(0);

  if (!empty($client_id)) {
    return $client_id;
  }
  return array();
}

/**
 *  Coach Dashboard
 */
function get_all_client_data_for_coach() {
  global $user;
  $coach_id = $user->uid;
  $role_id = db_query("Select rid from role where name = 'client'")->fetch();
  $client_name = $client_data = array();

  if (!empty($role_id)) {
    $rid = $role_id->rid;
  }

  $query = db_select('node', 'n')
    ->distinct();
  $query->join('field_data_field_coach_ref', 'coach', "coach.entity_id = n.nid");
  $query->join('field_data_field_client_ref', 'client', "client.entity_id = n.nid");
  $query->join('field_data_field_goal', 'goal', "goal.entity_id = n.nid");
  $query->join('users', 'at', "client.field_client_ref_target_id = at.uid");
  $query->join('field_data_field_first_name', 'fn', "fn.entity_id = at.uid");
  $query->join('field_data_field_last_name', 'ln', "ln.entity_id = at.uid");
  $query->join('users_roles', 'role', "role.uid = at.uid");
  $query->condition('role.rid', $rid);
  $query->condition('n.type', 'goals');
  $query->condition('coach.field_coach_ref_target_id', $coach_id);
  $query->fields('fn', array('field_first_name_value'));
  $query->fields('ln', array('field_last_name_value'));
  $query->fields('goal', array('field_goal_value'));
  $query->fields('n', array('nid'));
  $query->condition('at.status', 1);
  $client_id = $query->execute()->fetchAll();
  if (!empty($client_id)) {
    foreach ($client_id as $key => $value) {
      $client_data[$key]['first_name'] = $value->field_first_name_value;
      $client_data[$key]['last_name'] = $value->field_last_name_value;
      $client_data[$key]['goal'] = $value->field_goal_value;
      $client_data[$key]['remaining_days'] = get_remaining_days($value->nid);
    }
  }

  $variables = array();
  $variables = $client_data;
  $output = theme('coach_dashboard', array('coach_dashboard' => $variables));

  return $output;
}
