<?php
/**
 * @file
 * feature_ct_path_to_fitness.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function feature_ct_path_to_fitness_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_check_in_sessions'.
  $field_bases['field_check_in_sessions'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_check_in_sessions',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        '1-4w' => ' 1 Every 4 Weeks',
        '1-6w ' => ' 1 Every 6 Weeks',
        '1-8w ' => ' 1 Every 8 Weeks',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_client_ref'.
  $field_bases['field_client_ref'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_client_ref',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'views',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'view' => array(
          'args' => array(),
          'display_name' => 'entityreference_1',
          'view_name' => 'get_clients',
        ),
      ),
      'target_type' => 'user',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_daily_activity'.
  $field_bases['field_daily_activity'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_daily_activity',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        1 => ' 10000 steps',
        2 => ' 15000 steps',
        3 => ' 20000 steps',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_nutrition_protocol'.
  $field_bases['field_nutrition_protocol'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_nutrition_protocol',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        1 => ' 7 on 2 shakes 1 meal',
        2 => ' 5/2 split 2 shakes 1 meal alternating 2 meal 1 shake',
        3 => ' 3/4 split 2 shakes 1 meal alternating 2 meal 1 shake',
        4 => ' 2/5 split 2 shakes 1 meal alternating 2 meal 1 shake',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_re_feeds'.
  $field_bases['field_re_feeds'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_re_feeds',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        1 => ' 1 per week',
        2 => ' 2 per week',
        3 => ' 3 per week',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_recovery'.
  $field_bases['field_recovery'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_recovery',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        '2w ' => '2/ Week',
        '1w' => ' 1/ Week',
        '1f ' => '1/ Fortnight',
        '1m' => '1/ month',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_speciality_sessions'.
  $field_bases['field_speciality_sessions'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_speciality_sessions',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        '3pw' => ' 3 x /Week',
        '4pw' => ' 4 x /Week',
        '5pw' => ' 5 x /Week',
        '6pw' => ' 6 x /Week',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_total_training_sessions'.
  $field_bases['field_total_training_sessions'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_total_training_sessions',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'beginner' => ' 3 x /Week Beginner',
        'intermediate' => ' 4 x /Week Intermediate',
        'advanced' => ' 5 x/Week RxD Athlete',
        'competitor' => ' 6x /Week Competitor',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
